spring:
  application:
    name: user-management

  datasource:
    url: jdbc:postgresql://localhost:5432/knight_users
    username: knight
    password: knight_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: users

server:
  port: 8084

logging:
  level:
    com.knight: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
