micronaut:
  application:
    name: approval-workflow-engine
  server:
    port: 8085

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/knight_approvals
    driverClassName: org.postgresql.Driver
    username: knight
    password: knight
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
